use tcc 
go

select RELATORIO.ANO, RELATORIO.QUADRIMESTRE, FONTE.DESCRICAO FONTE, INFORMACAO.DESCRICAO INFORMACAO, PAGINA_INI, PAGINA_FIM from INDICADORES inner join 
(select * from informacao left join INFORMACAO_SINOMIMOS_Levenshtein_SOUNDEX on (
  ID = ID1 or ID = ID2 
)
where DESCRICAO in ('Total de Leitos SUS Curitiba', 'Rede Física de Serviços no SUS Curitiba')
) INFORM on (
  INFORMACAO_ID = ID OR INFORMACAO_ID = ID1 OR INFORMACAO_ID = ID2)
INNER JOIN RELATORIO ON (RELATORIO_ID = RELATORIO.ID)
INNER JOIN FONTE ON (FONTE_ID = FONTE.ID)
INNER JOIN INFORMACAO ON (INFORMACAO_ID = INFORMACAO.ID)