USE TCC
GO

/*Seção,Sub seção,Informação,Fonte Citada,Pagina,Só texto,Relatório,Observação,Link,Comentário relatório,Aberta,,,,,,,,,,,,,,,,,*/

/*
  DROP TABLE INDICADORES
  DROP TABLE INF
  DROP TABLE INF_LEVENSHTEIN
  DROP TABLE INF_SOUNDEX 
  DROP TABLE INF_LEVENSHTEIN_SOUNDEX
  DROP TABLE SECAO
  DROP TABLE SECAO_LEVENSHTEIN
  DROP TABLE SECAO_SOUNDEX 
  DROP TABLE SECAO_LEVENSHTEIN_SOUNDEX
  DROP TABLE SUBS_
  DROP TABLE SUBS_LEVENSHTEIN
  DROP TABLE SUBS_SOUNDEX 
  DROP TABLE SUBS_LEVENSHTEIN_SOUNDEX
  DROP TABLE SECAO
  DROP TABLE SUBSECAO
  DROP TABLE INF 
  DROP TABLE FONTE
  DROP TABLE RELATORIO
*/
CREATE TABLE SECAO_LIKE (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  DESCRICAO     VARCHAR(MAX)
)

CREATE TABLE SECAO (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES SECAO (ID),
  FOREIGN KEY (ID2) REFERENCES SECAO (ID)
)

CREATE TABLE SECAO_LEVENSHTEIN (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES SECAO (ID),
  FOREIGN KEY (ID2) REFERENCES SECAO (ID)
)

CREATE TABLE SECAO_SOUNDEX (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES SECAO (ID),
  FOREIGN KEY (ID2) REFERENCES SECAO (ID)
)

CREATE TABLE SECAO_LEVENSHTEIN_SOUNDEX (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES SECAO (ID),
  FOREIGN KEY (ID2) REFERENCES SECAO (ID)
)

CREATE TABLE SUBSECAO (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  DESCRICAO     VARCHAR(MAX)
)

CREATE TABLE SUBS_LIKE (
  ID1 INT,
  ID2 INT,
  CONSTRAINT PK_SUBSECAO_SINOMIMOS PRIMARY KEY(ID1, ID2),
  CONSTRAINT FK_SUBSECAO_SINOMIMOS1 FOREIGN KEY (ID1) REFERENCES SUBSECAO (ID),
  CONSTRAINT FK_SUBSECAO_SINOMIMOS2 FOREIGN KEY (ID2) REFERENCES SUBSECAO (ID)
)

CREATE TABLE SUBS_LEVENSHTEIN (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES SUBSECAO (ID),
  FOREIGN KEY (ID2) REFERENCES SUBSECAO (ID)
)

CREATE TABLE SUBS_SOUNDEX (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES SUBSECAO (ID),
  FOREIGN KEY (ID2) REFERENCES SUBSECAO (ID)
)

CREATE TABLE SUBS_LEVENSHTEIN_SOUNDEX (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES SUBSECAO (ID),
  FOREIGN KEY (ID2) REFERENCES SUBSECAO (ID)
)

CREATE TABLE INFORMACAO (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  DESCRICAO     VARCHAR(MAX)
)

CREATE TABLE INF_LIKE (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES INFORMACAO (ID),
  FOREIGN KEY (ID2) REFERENCES INFORMACAO (ID)
)

CREATE TABLE INF_LEVENSHTEIN (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES INFORMACAO (ID),
  FOREIGN KEY (ID2) REFERENCES INFORMACAO (ID)
)

CREATE TABLE INF_SOUNDEX (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES INFORMACAO (ID),
  FOREIGN KEY (ID2) REFERENCES INFORMACAO (ID)
)

CREATE TABLE INF_LEVENSHTEIN_SOUNDEX (
  ID1 INT,
  ID2 INT,
  PRIMARY KEY(ID1, ID2),
  FOREIGN KEY (ID1) REFERENCES INFORMACAO (ID),
  FOREIGN KEY (ID2) REFERENCES INFORMACAO (ID)
)

CREATE TABLE FONTE (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  DESCRICAO     VARCHAR(MAX)
)

CREATE TABLE RELATORIO (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  ANO           NUMERIC(4),
  QUADRIMESTRE  NUMERIC(1)
)

CREATE TABLE INDICADORES (
  RELATORIO_ID  INT,
  SECAO_ID      INT,
  SUBSECAO_ID   INT,
  INFORMACAO_ID INT,
  SEQ           INT,
  FONTE_ID      INT,
  PAGINA_INI    INT,
  PAGINA_FIM    INT,
  IND_TEXTO     VARCHAR(1),
  OBS           VARCHAR(MAX),
  LINK          VARCHAR(MAX),
  COM_REL       VARCHAR(MAX),
  CONSTRAINT PK_INDICADORES PRIMARY KEY(RELATORIO_ID, SECAO_ID, SUBSECAO_ID, INFORMACAO_ID, SEQ),
  CONSTRAINT FK_INDICADORES_RELATORIO  FOREIGN KEY (RELATORIO_ID ) REFERENCES RELATORIO  (ID),
  CONSTRAINT FK_INDICADORES_SECAO      FOREIGN KEY (SECAO_ID     ) REFERENCES SECAO      (ID),
  CONSTRAINT FK_INDICADORES_SUBSECAO   FOREIGN KEY (SUBSECAO_ID  ) REFERENCES SUBSECAO   (ID),
  CONSTRAINT FK_INDICADORES_INFORMACAO FOREIGN KEY (INFORMACAO_ID) REFERENCES INFORMACAO (ID),
  CONSTRAINT FK_INDICADORES_FONTE      FOREIGN KEY (FONTE_ID)      REFERENCES FONTE      (ID)
)