USE TCC
GO

/*Seção,Sub seção,Informação,Fonte Citada,Pagina,Só texto,Relatório,Observação,Link,Comentário relatório,Aberta,,,,,,,,,,,,,,,,,*/

/*
  DROP TABLE INDICADORES
  DROP TABLE SECAO
  DROP TABLE SUBSECAO
  DROP TABLE INFORMACAO 
  DROP TABLE FONTE
  DROP TABLE RELATORIO
*/
CREATE TABLE SECAO (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  DESCRICAO     VARCHAR(MAX)
)

CREATE TABLE SUBSECAO (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  DESCRICAO     VARCHAR(MAX)
)

CREATE TABLE INFORMACAO (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  DESCRICAO     VARCHAR(MAX)
)

CREATE TABLE FONTE (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  DESCRICAO     VARCHAR(MAX)
)

CREATE TABLE RELATORIO (
  ID            INT IDENTITY(1, 1) PRIMARY KEY,
  ANO           NUMERIC(4),
  TRIMESTRE     NUMERIC(1)
)



CREATE TABLE INDICADORES (
  RELATORIO_ID  INT,
  SECAO_ID      INT,
  SUBSECAO_ID   INT,
  INFORMACAO_ID INT,
  SEQ           INT,
  FONTE_ID      INT,
  PAGINA_INI    INT,
  PAGINA_FIM    INT,
  IND_TEXTO     VARCHAR(1),
  OBS           VARCHAR(MAX),
  LINK          VARCHAR(MAX),
  COM_REL       VARCHAR(MAX),
  CONSTRAINT PK_INDICADORES PRIMARY KEY(RELATORIO_ID, SECAO_ID, SUBSECAO_ID, INFORMACAO_ID, SEQ),
  CONSTRAINT FK_INDICADORES_RELATORIO  FOREIGN KEY (RELATORIO_ID ) REFERENCES RELATORIO  (ID),
  CONSTRAINT FK_INDICADORES_SECAO      FOREIGN KEY (SECAO_ID     ) REFERENCES SECAO      (ID),
  CONSTRAINT FK_INDICADORES_SUBSECAO   FOREIGN KEY (SUBSECAO_ID  ) REFERENCES SUBSECAO   (ID),
  CONSTRAINT FK_INDICADORES_INFORMACAO FOREIGN KEY (INFORMACAO_ID) REFERENCES INFORMACAO (ID),
  CONSTRAINT FK_INDICADORES_FONTE      FOREIGN KEY (FONTE_ID)      REFERENCES FONTE      (ID)
)