USE TCC
GO

INSERT INTO SECAO_SINOMIMOS_Levenshtein_SOUNDEX
SELECT 
  A.ID, 
  B.ID
FROM 
  SECAO_SINOMIMOS_Levenshtein
  INNER JOIN SECAO A ON ID1 = A.ID
  INNER JOIN SECAO B ON ID2 = B.ID 
WHERE 
  DIFFERENCE(A.DESCRICAO, B.DESCRICAO) > 3

INSERT INTO SUBSECAO_SINOMIMOS_Levenshtein_SOUNDEX
SELECT 
  A.ID, 
  B.ID
FROM 
  SUBSECAO_SINOMIMOS_Levenshtein
  INNER JOIN SUBSECAO A ON ID1 = A.ID
  INNER JOIN SUBSECAO B ON ID2 = B.ID 
WHERE 
  DIFFERENCE(A.DESCRICAO, B.DESCRICAO) > 3

INSERT INTO INFORMACAO_SINOMIMOS_Levenshtein_SOUNDEX
SELECT 
  A.ID, 
  B.ID
FROM 
  INFORMACAO_SINOMIMOS_Levenshtein
  INNER JOIN INFORMACAO A ON ID1 = A.ID
  INNER JOIN INFORMACAO B ON ID2 = B.ID 
WHERE 
  DIFFERENCE(A.DESCRICAO, B.DESCRICAO) > 3