INSERT INTO INFORMACAO_SINOMIMOS_Levenshtein
SELECT 
  A.ID, 
  B.ID
FROM 
  INFORMACAO_SINOMIMOS 
  INNER JOIN INFORMACAO A ON ID1 = A.ID
  INNER JOIN INFORMACAO B ON ID2 = B.ID 
WHERE 
  DBO.EDIT_DISTANCE_WITHIN(A.DESCRICAO, B.DESCRICAO, 25) <> -1


  