INSERT INTO INFORMACAO_SINOMIMOS
SELECT A.ID, B.ID FROM 
  INFORMACAO A INNER JOIN INFORMACAO B ON(
   (TRIM(REPLACE(A.DESCRICAO, '"', '')) LIKE '%' + TRIM(REPLACE(B.DESCRICAO, '"', '')) + '%' AND B.DESCRICAO <> ''))
  WHERE
   A.ID <> B.ID
GROUP BY
  A.ID,
  B.ID