USE TCC
GO

INSERT INTO SECAO_SINOMIMOS
SELECT A.ID, B.ID FROM 
  SECAO A INNER JOIN SECAO B ON(
   (TRIM(REPLACE(A.DESCRICAO, '"', '')) LIKE '%' + TRIM(REPLACE(B.DESCRICAO, '"', '')) + '%' AND B.DESCRICAO <> ''))
  WHERE
   A.ID <> B.ID
GROUP BY
  A.ID,
  B.ID


INSERT INTO SUBSECAO_SINOMIMOS
SELECT A.ID, B.ID FROM 
  SUBSECAO A INNER JOIN SUBSECAO B ON(
   (TRIM(REPLACE(A.DESCRICAO, '"', '')) LIKE '%' + TRIM(REPLACE(B.DESCRICAO, '"', '')) + '%' AND B.DESCRICAO <> ''))
  WHERE
   A.ID <> B.ID
GROUP BY
  A.ID,
  B.ID

INSERT INTO INFORMACAO_SINOMIMOS
SELECT A.ID, B.ID FROM 
  INFORMACAO A INNER JOIN INFORMACAO B ON(
   (TRIM(REPLACE(A.DESCRICAO, '"', '')) LIKE '%' + TRIM(REPLACE(B.DESCRICAO, '"', '')) + '%' AND B.DESCRICAO <> ''))
  WHERE
   A.ID <> B.ID
GROUP BY
  A.ID,
  B.ID

